[tool.poetry]
name = "pytenzir"
version = "4.2.0"
description = "A security telemetry engine for detection and response"
authors = ["Tenzir <engineering@tenzir.com>"]
maintainers = ["Tenzir <engineering@tenzir.com>"]
license = "BSD-3-Clause"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Plugins",
    "License :: OSI Approved :: BSD License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
    "Topic :: Security",
    "Topic :: Software Development :: Object Brokering",
    "Topic :: System :: Distributed Computing",
]
homepage = "https://tenzir.com"
documentation = "https://tenzir.com/docs"
repository = "https://github.com/tenzir/tenzir"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8"
coloredlogs = "^15.0"
dynaconf = "^3.2"
numpy = "^1.24"
pandas = ">=1.5,<3.0"
pyarrow = ">=11,<15"

[tool.poetry.dev-dependencies]
pytest = "^7.4"
pytest-asyncio = "^0.21.1"

[tool.pytest.ini_options]
asyncio_mode = "auto" # required for async fixtures

[tool.poetry.extras]
thehive = ["aiohttp"]

[tool.poetry.scripts]
app-thehive-run = { callable = "pytenzir.apps.thehive:run", extras = ["thehive"] }
app-thehive-count-alerts = { callable = "pytenzir.apps.thehive:count_alerts", extras = ["thehive"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
