name: Nix
on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  tenzir:
    name: Tenzir
    runs-on: ubuntu-20.04
    steps:
      - name: Prevent pushing protected editions to public repos
        run: |
          # Create 'name registry' pairs
          jq -r '.editions[] | select(."image-registries" | length > 0) | .name as $name | ."image-registries"[]? // ."image-registries" | [ $name, . ] | join(" ")' \
            <<< '${{ inputs.config }}' | while read -r name registry; do
            # Explicitly allow open source images.
            [[ "${name}" =~ ^tenzir$ ]] && continue
            # Explicitly allow private registries.
            [[ "${registry}" == "622024652768.dkr.ecr.eu-west-1.amazonaws.com" ]] && continue
            echo "::error Pushing ${name} to ${registry} is forbidden"
            exit 1
          done
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure
        id: cfg
        run: |
          # Configure
          echo '::notice triggered by: ${{ github.event_name }}'
          echo '::notice inputs = ${{ toJSON(fromJSON(inputs.config)) }}'
          echo "::notice checking registries..."
          echo "needs-docker-hub=false" >> "$GITHUB_OUTPUT"
          echo "needs-ghcr=false" >> "$GITHUB_OUTPUT"
          echo "needs-ecr=false" >> "$GITHUB_OUTPUT"
          jq -r '.editions | map( ."image-registries"[]) | unique | .[]
                 | if . == "docker.io" then
                     "needs-docker-hub=true"
                   elif . == "ghcr.io" then
                     "needs-ghcr=true"
                   elif . == "622024652768.dkr.ecr.eu-west-1.amazonaws.com" then
                     "needs-ecr=true"
                   else
                     empty
                   end
                 | @text' \
                 <<< '${{ inputs.config }}' >> "${GITHUB_OUTPUT}"
          echo "::notice checking tenzir-plugins..."
          jq -r '@text "upload-to-github=\(.editions | any(."upload-package-to-github"))"' \
                   <<< '${{ inputs.config }}' >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
      - name: Check outputs
        run: |
          echo 'cfg outputs: ${{ toJSON(steps.cfg.outputs) }}'
      - name: Configure ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.TENZIR_PLUGINS_DEPLOY_KEY }}
      - name: Login to GitHub Container Registry
        if: steps.cfg.outputs.needs-ghcr == 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tenzir-bot
          password: ${{ secrets.TENZIR_BOT_GITHUB_TOKEN }}
      - name: Login to Docker Hub
        if: steps.cfg.outputs.needs-docker-hub == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Configure AWS Credentials
        if: steps.cfg.outputs.needs-ecr == 'true'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::622024652768:role/ecr-tenzir-ce-github-access
          aws-region: eu-west-1
      - name: Login to AWS ECR
        if: steps.cfg.outputs.needs-ecr == 'true'
        uses: aws-actions/amazon-ecr-login@v1
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
        with:
          # disables telemetry
          diagnostic-endpoint: ""
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: tenzir
          authToken: "${{ secrets.CACHIX_TENZIR_API_TOKEN }}"
          # Avoid pushing the full enterprise edition.
          pushFilter: "tenzir-ee"
      - name: Build Nix Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RCLONE_GCS_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GCS_SERVICE_ACCOUNT_CREDENTIALS }}
          RCLONE_GCS_BUCKET_POLICY_ONLY: True
        run: |
          nix shell \
            nixpkgs#git \
            nixpkgs#nushell \
            nixpkgs#rclone \
            nixpkgs#skopeo \
            -c .github/workflows/nix.nu '${{ inputs.config }}'
      - name: Upload Tarball to Github
        if: steps.cfg.outputs.upload-to-github == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: tarball
          path: "./packages/tarball/*.tar.gz"
          if-no-files-found: ignore
      - name: Upload Debian Package to Github
        if: steps.cfg.outputs.upload-to-github == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: debian
          path: "./packages/debian/*.deb"
          if-no-files-found: ignore
